# GitHub Sentinel Configuration
# Copy this file to config.yaml and fill in your details.

github:
  token: "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" # Required. Generate from GitHub settings.

summarizer:
  # 'ai' 使用 LLM 生成智能摘要 (需要配置下面的 'llm' 部分)。
  # 'simple' 生成一个格式化的、未经 AI 处理的原始更新列表。
  type: "simple"

llm:
  provider: "openai" # or "gemini", "anthropic" etc. (future support)
  api_key: "your_openai_api_key" # Required.
  model: "gpt-4o-mini" # A cost-effective and capable model.

database:
  path: "./sentinel.db" # Path to the SQLite database file.

notifications:
  slack:
    enabled: true
    webhook_url: "your_slack_webhook_url"
  discord:
    enabled: false
    webhook_url: "your_discord_webhook_url"
  email:
    enabled: false
    # smtp_server: "smtp.example.com"
    # smtp_port: 587
    # ... more email settings
